"""add notifications column in user

Revision ID: 4077149a12f8
Revises: 7cf91161df2b
Create Date: 2025-11-15 23:48:37.522746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4077149a12f8'
down_revision: Union[str, Sequence[str], None] = '7cf91161df2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('query_parameters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('query_parameters', 'per_page',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('query_parameters', 'page',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('query_parameters', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('query_parameters', 'experience',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('query_parameters', 'area',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('query_parameters', 'only_with_salary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('query_parameters', 'period',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('query_parameters', 'order_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('query_parameters', 'accept_temporary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('query_parameters', 'employment_form',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('query_parameters', 'work_format',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('query_parameters', 'salary',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('notifications', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications')
    op.alter_column('query_parameters', 'salary',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('query_parameters', 'work_format',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('query_parameters', 'employment_form',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('query_parameters', 'accept_temporary',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('query_parameters', 'order_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('query_parameters', 'period',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('query_parameters', 'only_with_salary',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('query_parameters', 'area',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('query_parameters', 'experience',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('query_parameters', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('query_parameters', 'page',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('query_parameters', 'per_page',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('query_parameters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
