"""add nullable true to every column in queryparameters

Revision ID: 7a8e07ffd91d
Revises: 9b0f697ee9ca
Create Date: 2025-11-16 00:07:46.345173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8e07ffd91d'
down_revision: Union[str, Sequence[str], None] = '9b0f697ee9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('query_parameters', 'per_page',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('query_parameters', 'page',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('query_parameters', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('query_parameters', 'experience',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('query_parameters', 'area',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('query_parameters', 'only_with_salary',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('query_parameters', 'period',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('query_parameters', 'order_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('query_parameters', 'employment_form',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('query_parameters', 'work_format',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('query_parameters', 'salary',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('query_parameters', 'salary',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('query_parameters', 'work_format',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('query_parameters', 'employment_form',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('query_parameters', 'order_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('query_parameters', 'period',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('query_parameters', 'only_with_salary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('query_parameters', 'area',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('query_parameters', 'experience',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('query_parameters', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('query_parameters', 'page',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('query_parameters', 'per_page',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
