"""add page

Revision ID: 7cf91161df2b
Revises: 63e785e6752e
Create Date: 2025-11-13 23:22:32.451517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf91161df2b'
down_revision: Union[str, Sequence[str], None] = '63e785e6752e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_parameters', sa.Column('page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_parameters', 'page')
    # ### end Alembic commands ###
