"""removed filter, added query parameters

Revision ID: 97fe7613c847
Revises: d728b4517910
Create Date: 2025-11-13 01:08:45.492672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97fe7613c847'
down_revision: Union[str, Sequence[str], None] = 'd728b4517910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('per_page', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('only_with_salary', sa.Boolean(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('order_by', sa.String(), nullable=True),
    sa.Column('accept_temporary', sa.Boolean(), nullable=True),
    sa.Column('employment_form', sa.String(), nullable=True),
    sa.Column('work_schedule_by_days', sa.String(), nullable=True),
    sa.Column('working_hours', sa.String(), nullable=True),
    sa.Column('work_format', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('filters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remote', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('currency_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('search_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('filters_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('filters_pkey'))
    )
    op.drop_table('query_parameters')
    # ### end Alembic commands ###
