"""add notifications column in user

Revision ID: 9b0f697ee9ca
Revises: c088e1e1581e
Create Date: 2025-11-15 23:59:16.687275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0f697ee9ca'
down_revision: Union[str, Sequence[str], None] = 'c088e1e1581e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('query_parameters', 'accept_temporary',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('query_parameters', 'accept_temporary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
