"""add notifications column in user

Revision ID: c088e1e1581e
Revises: 4077149a12f8
Create Date: 2025-11-15 23:53:38.718899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c088e1e1581e'
down_revision: Union[str, Sequence[str], None] = '4077149a12f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('query_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('per_page', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('experience', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('only_with_salary', sa.Boolean(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('order_by', sa.String(), nullable=False),
    sa.Column('accept_temporary', sa.Boolean(), nullable=False),
    sa.Column('employment_form', sa.String(), nullable=False),
    sa.Column('work_format', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_parameters')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
