"""changed columns in filter

Revision ID: d728b4517910
Revises: e8139d8c0fae
Create Date: 2025-11-13 00:39:43.460817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd728b4517910'
down_revision: Union[str, Sequence[str], None] = 'e8139d8c0fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filters', sa.Column('remote', sa.Boolean(), nullable=True))
    op.add_column('filters', sa.Column('salary', sa.Integer(), nullable=True))
    op.add_column('filters', sa.Column('currency_code', sa.String(), nullable=True))
    op.add_column('filters', sa.Column('experience', sa.String(), nullable=True))
    op.add_column('filters', sa.Column('search_period', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filters', 'search_period')
    op.drop_column('filters', 'experience')
    op.drop_column('filters', 'currency_code')
    op.drop_column('filters', 'salary')
    op.drop_column('filters', 'remote')
    # ### end Alembic commands ###
