"""modified queryparameters columns

Revision ID: f71db53ce6d7
Revises: 97fe7613c847
Create Date: 2025-11-13 17:07:57.442735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71db53ce6d7'
down_revision: Union[str, Sequence[str], None] = '97fe7613c847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_parameters', sa.Column('salary', sa.Integer(), nullable=True))
    op.drop_column('query_parameters', 'label')
    op.drop_column('query_parameters', 'working_hours')
    op.drop_column('query_parameters', 'education')
    op.drop_column('query_parameters', 'work_schedule_by_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_parameters', sa.Column('work_schedule_by_days', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('query_parameters', sa.Column('education', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('query_parameters', sa.Column('working_hours', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('query_parameters', sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('query_parameters', 'salary')
    # ### end Alembic commands ###
